imgmanip: homography.h File Reference
homography.h File Reference
#include <iostream>
#include <vector>
#include "imgio/imgio.h"
Functions
template<typename rowColType >
mat computeHomography (Mat< rowColType > &srcPts, Mat< rowColType > &destPts)
Given source points and destination points, compute homography matrix.
template<typename rowColType >
Mat< int > applyHomography (mat H_3x3, Mat< rowColType > srcPtsSqueezed)
Apply the homography matrix.
vector< int > getNewCanvasDims (Cube< int > &srcImg, mat &H_3x3)
Get the New Canvas Dimentions.
template<NumericType pixel_type>
Cube< pixel_type > genHomographyImgCanvas (Cube< int > &srcImg, mat &H_3x3)
get the warped image
void homographyCommandLine (string srcImgPath, string homogType)
The command line for the homography.
Function Documentation
applyHomography()
template<typename rowColType > Mat< int > applyHomography (mat H_3x3, Mat< rowColType > srcPtsSqueezed)
Apply the homography matrix.
Template Parameters
rowColType the pixel type
Parameters
H_3x3 the homography matrix
srcPtsSqueezed the source points
Returns
Mat<int> the computed desintation
Referenced by genHomographyImgCanvas(), and getNewCanvasDims().
computeHomography()
template<typename rowColType > mat computeHomography (Mat< rowColType > & srcPts, Mat< rowColType > & destPts)
Given source points and destination points, compute homography matrix.
Template Parameters
rowColType the pixel type
Parameters
srcPts the source points
destPts the destination points
Returns
mat the homography matrix
Referenced by homographyCommandLine().
genHomographyImgCanvas()
template<NumericType pixel_type> Cube< pixel_type > genHomographyImgCanvas (Cube< int > & srcImg, mat & H_3x3)
get the warped image
Template Parameters
pixel_type the type of pixel
Parameters
srcImg the souce image
H_3x3 the homography matrix
Returns
Cube<pixel_type> the warped image
References applyHomography(), and getNewCanvasDims().
getNewCanvasDims()
vector< int > getNewCanvasDims (Cube< int > & srcImg, mat & H_3x3)
Get the New Canvas Dimentions.
Parameters
srcImg the souce image
H_3x3 the homography matrix
Returns
vector<int> the number of rows and number of cols of the new image
References applyHomography().
Referenced by genHomographyImgCanvas().
homographyCommandLine()
void homographyCommandLine (string srcImgPath, string homogType)
The command line for the homography.
Parameters
srcImgPath the path of source image
homogType the type of homography – triangle, spiral, random
References computeHomography(), and write_img().