imgmanip: imgio/imgio.h File Reference
imgio.h File Reference
#include <iostream>
#include <functional>
#include <type_traits>
#include "pch.h"
Classes
struct PixelGenerator< pixel_type >
struct PixelReader< pixel_type >
Concepts
concept NumericType
Functions
template<NumericType pixel_type>
Cube< pixel_type > read_img (string filename)
Read the image.
template<NumericType pixel_type>
void write_img (Cube< pixel_type > &storage, string save_path)
Write from cube to an image.
string get_file_extension (string filename)
Get the extention of the image file (jpeg, jpg, png)
bool is_file_img (string filename)
Return whether the file is an image or not.
template<NumericType pixel_type>
vector< Cube< pixel_type > > read_many_imgs (vector< string > &filenames, function< Cube< pixel_type >(Cube< pixel_type >)> pipeline)
Read more than one images.
Function Documentation
get_file_extension()
string get_file_extension (string filename)
Get the extention of the image file (jpeg, jpg, png)
Parameters
filename the name of the image file
Returns
string the extention of the img file
Referenced by is_file_img(), read_img(), and write_img().
is_file_img()
bool is_file_img (string filename)
Return whether the file is an image or not.
Parameters
filename the name of the image file
Returns
whether the file is an image or not
References get_file_extension().
Referenced by create_mosaic().
read_img()
template<NumericType pixel_type> Cube< pixel_type > read_img (string filename)
Read the image.
Template Parameters
pixel_type the type of the pixel
Parameters
filename the name of the image file
Returns
Cube<pixel_type> the cube of the image representation
References get_file_extension().
read_many_imgs()
template<NumericType pixel_type> vector< Cube< pixel_type > > read_many_imgs (vector< string > & filenames, function< Cube< pixel_type >(Cube< pixel_type >)> pipeline)
Read more than one images.
Template Parameters
pixel_type the type of the pixel
Parameters
filenames the name of the image files
pipeline read in image pipeline function
Returns
vector<Cube<pixel_type>> the vector of cube representations in images
write_img()
template<NumericType pixel_type> void write_img (Cube< pixel_type > & storage, string save_path)
Write from cube to an image.
Template Parameters
pixel_type the type of the pixel
Parameters
storage the cube of the image representation
save_path the path to save the generated image
References get_file_extension().
Referenced by createMosaicCommandLine(), grayscaleCommandLine(), and homographyCommandLine().