imgmanip: mosaic.h File Reference
mosaic.h File Reference
#include <iostream>
#include <vector>
#include <functional>
#include <future>
#include "imgio/imgio.h"
#include <chrono>
#include <string>
#include <filesystem>
Classes
class PreprocessingException
Functions
template<NumericType pixel_type>
void coutImgAttr (Cube< pixel_type > &img)
Print the attribute of the image.
template<NumericType pixel_type>
Cube< pixel_type > crop (Cube< pixel_type > &srcImg, int left_top_r, int left_top_c, int w, int h)
Crop the image.
template<NumericType pixel_type>
Cube< pixel_type > maxCrop (Cube< pixel_type > &srcImg, double img_out_ratio)
Crop the max image with a specific ratio.
template<NumericType pixel_type>
vector< float > getAvgColor (Cube< pixel_type > &img)
Get the Avg Color.
template<NumericType pixel_type>
Cube< pixel_type > resize_image (Cube< pixel_type > &srcImg, int target_h, int target_w)
This function resize the image, it can be scaled up and scaled down.
template<NumericType pixel_type>
Cube< pixel_type > getBestMatch (Cube< pixel_type > &targetImg, vector< Cube< pixel_type > > &srcImg_List)
Find the best match based on the euclidean distance among the list of source images and return that specific img.
template<NumericType pixel_type>
int getBestMatchIdx (vector< float > targetAvgColor, vector< vector< float > > &srcAvgColors)
Get the Best Match index of the image between target average color and the source average colors.
template<NumericType pixel_type>
tuple< Cube< pixel_type >, vector< float > > init_tile (Cube< int > &srcImg, double img_out_ratio, int target_h, int target_w)
Construct a new tuple<Cube<pixel type>, vector<float>>init tile object to construct a tile The first element is the img of the tile and the second element is the avg color of that tile img.
template<typename T >
function< T(T)> makePipeline (const std::vector< std::function< T(T)> > &funcs)
Make the function application pipeline.
template<NumericType pixel_type>
void fill_image (Cube< pixel_type > &canvas, Cube< pixel_type > &tile, int left_top_r, int left_top_c)
Fill the canvas in the region starting from (left_top_r, left_top_c) with the pixels from tiles.
template<NumericType pixel_type>
bool isTileDense (Cube< pixel_type > &srcImg, int tile_h, int tile_w)
Return whether the tile is dense which means the source image number of rows >= tile_h and number of columns >= tile_w.
template<NumericType pixel_type>
Cube< pixel_type > create_mosaic (string tgt_img_path, string src_img_dir, int tile_cnt_h, int tile_cnt_w)
Create a mosaic version of the image on tgt_img_path from a list of images in the src_img_dir. The mosaic version of image has tile_cnt_h x tile_cnt_w mosaics.
void createMosaicCommandLine (string tgtImgPath, string srcImgDir)
Create a Mosaic Command Line.
Variables
PreprocessingException preprocessingException
Function Documentation
coutImgAttr()
template<NumericType pixel_type> void coutImgAttr (Cube< pixel_type > & img)
Print the attribute of the image.
Template Parameters
pixel_type the type of pixel
Parameters
img the image
create_mosaic()
template<NumericType pixel_type> Cube< pixel_type > create_mosaic (string tgt_img_path, string src_img_dir, int tile_cnt_h, int tile_cnt_w)
Create a mosaic version of the image on tgt_img_path from a list of images in the src_img_dir. The mosaic version of image has tile_cnt_h x tile_cnt_w mosaics.
Template Parameters
pixel_type The type of the pixel
Parameters
tgt_img_path the path to the target image
src_img_dir the directory containing potential mosaics
tile_cnt_h the number of tiles in a column of the resulting image
tile_cnt_w the number of tiles in a row of the resulting image
References crop(), fill_image(), getBestMatch(), is_file_img(), maxCrop(), and preprocessingException.
createMosaicCommandLine()
void createMosaicCommandLine (string tgtImgPath, string srcImgDir)
Create a Mosaic Command Line.
Parameters
tgtImgPath the target image path
srcImgDir the source image directory
References write_img().
crop()
template<NumericType pixel_type> Cube< pixel_type > crop (Cube< pixel_type > & srcImg, int left_top_r, int left_top_c, int w, int h)
Crop the image.
Template Parameters
pixel_type the type of pixel
Parameters
srcImg the source image
left_top_r left top row
left_top_c left top column
w width
h height
Returns
Cube<pixel_type> cropped image
Referenced by create_mosaic().
fill_image()
template<NumericType pixel_type> void fill_image (Cube< pixel_type > & canvas, Cube< pixel_type > & tile, int left_top_r, int left_top_c)
Fill the canvas in the region starting from (left_top_r, left_top_c) with the pixels from tiles.
Template Parameters
pixel_type The type of the pixel
Parameters
canvas canvas to fill on
tile source tile image
left_top_r the starting pixel coordinate r on canvas
left_top_c the starting pixel coordinate c on canvas
Referenced by create_mosaic().
getAvgColor()
template<NumericType pixel_type> vector< float > getAvgColor (Cube< pixel_type > & img)
Get the Avg Color.
Template Parameters
pixel_type the type of the pixel
Parameters
img the image
Returns
vector<float> the avgerage of red, green and blue channel
Referenced by getBestMatch(), and init_tile().
getBestMatch()
template<NumericType pixel_type> Cube< pixel_type > getBestMatch (Cube< pixel_type > & targetImg, vector< Cube< pixel_type > > & srcImg_List)
Find the best match based on the euclidean distance among the list of source images and return that specific img.
Template Parameters
pixel_type the type of the pixel
Parameters
targetImg the target img we hope to compared with
srcImg_List the list of sourced images
Returns
Cube<pixel_type> the img that we has the best match with the target img
References getAvgColor().
Referenced by create_mosaic().
getBestMatchIdx()
template<NumericType pixel_type> int getBestMatchIdx (vector< float > targetAvgColor, vector< vector< float > > & srcAvgColors)
Get the Best Match index of the image between target average color and the source average colors.
Template Parameters
pixel_type the pixel type
Parameters
targetAvgColor the target average color
srcAvgColors the list of the average colors of different courses image
Returns
int the best match index
init_tile()
template<NumericType pixel_type> tuple< Cube< pixel_type >, vector< float > > init_tile (Cube< int > & srcImg, double img_out_ratio, int target_h, int target_w)
Construct a new tuple<Cube<pixel type>, vector<float>>init tile object to construct a tile The first element is the img of the tile and the second element is the avg color of that tile img.
Template Parameters
pixel_type The type of the pixel
Parameters
srcImg The source img
img_out_ratio The img w/h
target_h The height of the target img
target_w The width of the target img
References getAvgColor(), maxCrop(), and resize_image().
isTileDense()
template<NumericType pixel_type> bool isTileDense (Cube< pixel_type > & srcImg, int tile_h, int tile_w)
Return whether the tile is dense which means the source image number of rows >= tile_h and number of columns >= tile_w.
Template Parameters
pixel_type the type of pixel
Parameters
srcImg the source image
tile_h the tile heigh
tile_w the tile weight
Returns
whether the tile is dense
makePipeline()
template<typename T > function< T(T)> makePipeline (const std::vector< std::function< T(T)> > & funcs)
Make the function application pipeline.
Template Parameters
T The generic type
Parameters
funcs
Returns
function<T (T)>
maxCrop()
template<NumericType pixel_type> Cube< pixel_type > maxCrop (Cube< pixel_type > & srcImg, double img_out_ratio)
Crop the max image with a specific ratio.
Template Parameters
pixel_type the type of pixel
Parameters
srcImg the source image
img_out_ratio the width/height
Returns
Cube<pixel_type> the cropped image
Referenced by create_mosaic(), and init_tile().
resize_image()
template<NumericType pixel_type> Cube< pixel_type > resize_image (Cube< pixel_type > & srcImg, int target_h, int target_w)
This function resize the image, it can be scaled up and scaled down.
Template Parameters
pixel_type The type of the pixel
Parameters
srcImg The source img
target_h The height of the target resized img
target_w The width of the target resized img
Returns
Cube<pixel_type>
Referenced by init_tile().
Variable Documentation
preprocessingException
PreprocessingException preprocessingException
Referenced by create_mosaic().